services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: grpcdb
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=root"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - app-network

  app:
    image: golang:1.22-alpine
    container_name: grpc-app
    working_dir: /go/src/app
    volumes:
      - .:/go/src/app  # ホストのカレントディレクトリをコンテナにマウント
    command: go run cmd/server/main.go
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: grpcdb
    networks:
      - app-network

networks:
  app-network:
